# Configuramos el puerto de la aplicación
server:
  port: 8080

spring:
  # Nombre del microservicio
  application:
    name: ms-user
  # Configuración de la base de datos
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    username: ${USERNAME_DB:postgres}
    password: ${PASSWORD_DB:password}
    url: ${URL_DB:jdbc:postgresql://localhost:5432/ucb_sisacademico}
  jpa:
    hibernate:
      ddl-auto: update
      # Para crear una entidad si es que no existe en la bd
