## Agregar nuevo estudiante
POST http://localhost:8080/api/v1/student
Accept: application/json
Content-Type: application/json

{
    "nombre": "Juan Jose",
    "apellidoPaterno": "Perez",
    "apellidoMaterno": "Garcia",
    "carnetIdentidad": "12345678",
    "fechaNacimiento": "1999-01-01",
    "correo": "juan.perez.abc@ucb.edu.bo",
    "genero": "Hombre",
    "celular": "123456789",
    "descripcion": "Hola, soy Juan Perez",
    "uuidFoto": "./assets/icons/usuario.png",
    "uuidPortada": "./assets/icons/portada-arboles.jpg",
    "direccion": "Calle 1",
    "fechaRegistro": "2021-01-01",
    "estadoCivil": "Soltero/a",
    "username": "juan.perez",
    "secret": "123456",
    "rol": "estudiante",
    "semestre": 1,
    "colegioId": 1,
    "carreraId": 1,
    "estado": true
}

###
## Obtener un estudiante por id
GET http://localhost:8080/api/v1/student/2

###
## Obtener todos los estudiantes
GET http://localhost:8080/api/v1/student?page=0&size=10



###
## Actualizar un estudiante
PUT http://localhost:8080/api/v1/student/2
Accept: application/json
Content-Type: application/json

{
  "nombre": "Juan Pablo",
  "apellidoPaterno": "Gonzales",
  "apellidoMaterno": "Lopez x",
  "carnetIdentidad": "89322",
  "fechaNacimiento": "2023-01-01",
  "correo": "juan.gonzalesaaa@ucb.edu.bo",
  "genero": "Hombre,",
  "celular": "123456789",
  "descripcion": "",
  "uuidFoto": "./assets/icons/usuario.png",
  "uuidPortada": "./assets/icons/portada-arboles.jpg",
  "direccion": "Calle 1",
  "fechaRegistro": "2021-01-01",
  "estadoCivil": "Casado/a",
  "username": "juan.perez",
  "secret": "juanperez",
  "rol": "estudiante",
  "semestre": 1,
  "colegioId": 1,
  "carreraId": 1,
  "estado": true
}


