## Agregar docente

POST http://localhost:8080/api/v1/teacher
Accept: application/json
Content-Type: application/json

{
    "nombre": "Roberta",
    "apellidoPaterno": "Gonzalez",
    "apellidoMaterno": "Perez",
    "carnetIdentidad": "1234567897563689",
    "fechaNacimiento": "1990-01-01",
    "correo": "roberta.gonzales8@gmail.com",
    "genero": "Mujer",
    "celular": "123456781",
    "descripcion": "",
    "uuidFoto": "./assets/icons/usuario.png",
    "uuidPortada": "./assets/icons/portada-arboles.jpg",
    "direccion": "Av. America #1234",
    "fechaRegistro": "2021-01-01",
    "estadoCivil": "Soltero/a",
    "username": "roberta.gonzalez",
    "secret": "12345678",
    "rol": "Docente",
    "tipo": "Tiempo completo",
    "profesionId": 1,
    "departamentoCarreraId": 1,
    "directorCarrera": false,
    "estado": true
}

###
## Obtener docente por id
GET http://localhost:8080/api/v1/teacher/1


###
## Actualizar docente
PUT http://localhost:8080/api/v1/teacher/1
Accept: application/json
Content-Type: application/json

{
  "nombre": "Roberta",
  "apellidoPaterno": "Gonzalez",
  "apellidoMaterno": "Perez",
  "carnetIdentidad": "12345678",
  "fechaNacimiento": "1990-01-01",
  "correo": "roberta.gonzalezaaa@gmail.com",
  "genero": "Mujer :D",
  "celular": "12345678",
  "descripcion": "",
  "uuidFoto": "./assets/icons/usuario.png",
  "uuidPortada": "./assets/icons/portada-arboles.jpg",
  "direccion": "Av. America #1234",
  "fechaRegistro": "2023-01-01",
  "estadoCivil": "Soltero/a",
  "username": "roberta.gonzalez",
  "secret": "1234567899",
  "rol": "Docente",
  "tipo": "Tiempo completo",
  "profesionId": 1,
  "departamentoCarreraId": 1,
  "directorCarrera": true,
  "estado": true
}