### Obtener usuario por id

GET http://localhost:8080/api/v1/user/4


### Obtener usuario por su token
GET http://localhost:8080/api/v1/user
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzWIiOiIyIiwiZXhwIjoxNjk2NjM2MDgyLCJpc3MiOiJVQ0IiLCJyZWZyZXNoIjpmYWxzZX0.3yVgolP0Kt0FrAPz-bO1ohIFFAP7uJsIPUcttkiahr0