### Obtener usuario por id

GET http://localhost:8080/api/v1/user/4


### Obtener usuario por su token
GET http://localhost:8080/api/v1/user
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwiZXhwIjoxNjk3MDg4MDM0LCJpc3MiOiJVQ0IiLCJyb2wiOiJFc3R1ZGlhbnRlIn0.6-rNhsS-pozcsw1d6Gx2YPT4kMVSF26SdoCOC2uOpus

### Obtener los amigos del usuario por su token
GET http://localhost:8080/api/v1/user/friend
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0IiwiZXhwIjoxNjk3MDk1NDU1LCJpc3MiOiJVQ0IiLCJyb2wiOiJFc3R1ZGlhbnRlIn0.TWmLa8AeHlmQ041jCH_x8xEx8jCggeaazF1O-pxjXUQ

### Obtener todas las notificaciones de amistad
GET http://localhost:8080/api/v1/user/friend/request
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwiZXhwIjoxNjk3MDg4MDM0LCJpc3MiOiJVQ0IiLCJyb2wiOiJFc3R1ZGlhbnRlIn0.6-rNhsS-pozcsw1d6Gx2YPT4kMVSF26SdoCOC2uOpus

### Mandar una solicitud de amistad
POST http://localhost:8080/api/v1/user/friend/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwiZXhwIjoxNjk3MDg4MDM0LCJpc3MiOiJVQ0IiLCJyb2wiOiJFc3R1ZGlhbnRlIn0.6-rNhsS-pozcsw1d6Gx2YPT4kMVSF26SdoCOC2uOpus

### Aceptar una solicitud de amistad
PUT http://localhost:8080/api/v1/user/friend/2/false
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0IiwiZXhwIjoxNjk3MDk1NDU1LCJpc3MiOiJVQ0IiLCJyb2wiOiJFc3R1ZGlhbnRlIn0.TWmLa8AeHlmQ041jCH_x8xEx8jCggeaazF1O-pxjXUQ

