### Obtener usuario por id
GET http://localhost:8080/api/v1/user/5


### Verificar si existe un usuario por su email
POST http://localhost:8080/api/v1/user/email
Content-Type: application/json
Accept: application/json

{
  "email": "elizabeth.tacachira@ucb.edu.bo"
}

### Obtener usuario por su token
GET http://localhost:8080/api/v1/user
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwiZXhwIjoxNjk3MDg4MDM0LCJpc3MiOiJVQ0IiLCJyb2wiOiJFc3R1ZGlhbnRlIn0.6-rNhsS-pozcsw1d6Gx2YPT4kMVSF26SdoCOC2uOpus

### Actualizar contraseña por token
PUT http://localhost:8080/api/v1/user/password
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwiZXhwIjoxNjk5OTQ1MDg0LCJpc3MiOiJVQ0IiLCJyb2wiOiJlc3R1ZGlhbnRlIn0.i12BSLiRDpKQT81mW-NNSnGWnWwH6SggVIfUKgJFQQw

{
  "currentPassword": "123456",
  "newPassword": "12345678",
  "confirmNewPassword": "12345678"
}

### Actualizar contraseña sin contraseña actual
PUT http://localhost:8080/api/v1/user/password/without
Content-Type: application/json
Accept: application/json

{
  "email": "elizabeth.tacachira@ucb.edu.bo",
  "newPassword": "12345678"
}


### Eliminar logicamente un usuario por su id
DELETE http://localhost:8080/api/v1/user/5


## AMIGOS
### Obtener los amigos del usuario por su id
GET http://localhost:8080/api/v1/user/2/friend


### Obtener todas las notificaciones de amistad
GET http://localhost:8080/api/v1/user/friend/request
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1IiwiZXhwIjoxNjk3MTQ5NzM3LCJpc3MiOiJVQ0IiLCJyb2wiOiJEb2NlbnRlIn0.hUS4k_2NZfSQtTMQ1gVK8peCjWMnp3hXYMJYMLoRoKI


### Mandar una solicitud de amistad
POST http://localhost:8080/api/v1/user/friend/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1IiwiZXhwIjoxNjk3MTQ5NzM3LCJpc3MiOiJVQ0IiLCJyb2wiOiJEb2NlbnRlIn0.hUS4k_2NZfSQtTMQ1gVK8peCjWMnp3hXYMJYMLoRoKI


### Aceptar una solicitud de amistad
PUT http://localhost:8080/api/v1/user/friend/5/true
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwiZXhwIjoxNjk3MTQ5OTEwLCJpc3MiOiJVQ0IiLCJyb2wiOiJEb2NlbnRlIn0.yTmqS1bqDahokfyUIOGuvIrssLq8ezpBcdaH4jo3kEA


### Eliminar a un amigo de la lista de amigos
DELETE http://localhost:8080/api/v1/user/friend/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1IiwiZXhwIjoxNjk3MTUxMTIyLCJpc3MiOiJVQ0IiLCJyb2wiOiJEb2NlbnRlIn0.T6mO4WIOCv3ZmgRPKSWSHSho6fO8XmitkG9OPfEZ53o

### Actualizar el perfil del usuario (propio)
PUT http://localhost:8080/api/v1/user/profile
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1IiwiZXhwIjoxNjk3MTUxMTIyLCJpc3MiOiJVQ0IiLCJyb2wiOiJEb2NlbnRlIn0.T6mO4WIOCv3ZmgRPKSWSHSho6fO8XmitkG9OPfEZ53o

{
  "descripcion": "Hola soy yo",
  "uuidFoto": "",
  "uuidPortada": ""
}


